apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-init-file-cm
data:
  init.sh: |-
    #!/bin/bash
    echo "==== Starting Automated On-Premise NFS Initialization ===="
    # 1. 도커 이미지 내부에 구워진 압축 파일을 공유 볼륨(/nfs)에 해제
    echo "Extracting ahnfs.tar.gz..."
    tar -zxvf /data/ahnfs.tar.gz -C /nfs/
    # 2. 이중 폴더(ahnfs/ahnfs)로 풀렸을 경우를 대비한 자동 정리 로직
    if [ -d "/nfs/ahnfs" ]; then
      mv /nfs/ahnfs/* /nfs/
      rm -rf /nfs/ahnfs
    fi
    # 3. 파드들이 접근할 수 있도록 넉넉한 권한 부여
    chmod -R 777 /nfs
    echo "==== NFS Initialization Completed Successfully! ===="
