{{- if .Values.nfsInit.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nfsInit.name }}-env-cm
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
data:
  INTERNAL_SERVICE: {{ .Values.internalService.name }}.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
