{{- if .Values.nfsInit.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.nfsInit.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-4"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: {{ .Values.nfsInit.restartPolicy | default "OnFailure" }}
      containers:
        - name: {{ .Values.nfsInit.name }}
          image: {{ .Values.nfsInit.repository }}:{{ .Values.nfsInit.version }}
          imagePullPolicy: {{ .Values.nfsInit.pullPolicy | default "IfNotPresent" }}
          volumeMounts:
          - name: nfs
            mountPath: /nfs
          - name: {{ .Values.nfsInit.name }}-file-cm
            mountPath: /init
          command: [/bin/bash, /init/init.sh]
      volumes:
      - name: nfs
        hostPath:
          path: {{ .Values.global.hostPathBase | default "/data/ahnfs" }}
          type: DirectoryOrCreate
      - name: {{ .Values.nfsInit.name }}-file-cm  
        configMap:
          name: {{ .Values.nfsInit.name }}-file-cm
          defaultMode: 0755
{{- end }}
