{{- if .Values.nfsInit.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nfsInit.name }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
type: Opaque
data:
  {{- range $path, $_ := .Files.Glob "cert/*" }}
  {{ $path | trimPrefix "cert/" }}: {{ $.Files.Get $path | b64enc }}
  {{ end }}
{{- end }}
