apiVersion: v1
kind: Service
metadata:
  name: test-web-service
spec:
  selector:
    app: test-web # Deployment의 label과 동일해야 서로 연결됩니다.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort 
