---
apiVersion: v1
kind: Service
metadata:
  name: cpp-mongo-mongos
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: epp-mongo-mongos
  ports:
    - port: 8825
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-pgbouncer-eppoltp
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: epp-pgbouncer-eppoltp
  ports:
    - port: 8819
      targetPort: 8819
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-postgres-eppoltp
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: epp-postgres-eppoltp
  ports:
    - port: 8817
      targetPort: 8817
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-redis
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: epp-redis
  ports:
    - port: 8831
      targetPort: 8831
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-kafka
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: epp-kafka
  ports:
    - port: 8816
      targetPort: 8816
      name: kafka-8816
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-eureka-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
    - port: 8807
      targetPort: 8807
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-eureka-gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: eureka-gateway
  ports:
    - port: 8804
      targetPort: 8804
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-lbagent
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: lbagent
  ports:
    - port: 8804
      targetPort: 8804
      protocol: TCP
