
apiVersion: v1

kind: Service

metadata:

  name: cpp-eureka-gateway

  namespace: {{ .Release.Namespace }}

spec:

  type: ExternalName

  externalName: epp-eureka-gateway.k8s-cppm.svc.cluster.local

---

apiVersion: v1

kind: Service

metadata:

  name: cpp-eureka-server

  namespace: {{ .Release.Namespace }}

spec:

  type: ExternalName

  externalName: epp-eureka-server.k8s-cppm.svc.cluster.local

---

apiVersion: v1

kind: Service

metadata:

  name: cpp-kafka

  namespace: {{ .Release.Namespace }}

spec:

  type: ExternalName

  externalName: epp-kafka.k8s-cppm.svc.cluster.local

---

apiVersion: v1

kind: Service

metadata:

  name: cpp-lbagent

  namespace: {{ .Release.Namespace }}

spec:

  type: ExternalName

  externalName: epp-lbagent.k8s-cppm.svc.cluster.local

---

apiVersion: v1

kind: Service

metadata:

  name: cpp-mongo-mongos

  namespace: {{ .Release.Namespace }}

spec:

  type: ExternalName

  externalName: epp-mongo-mongos.k8s-cppm.svc.cluster.local

---

apiVersion: v1

kind: Service

metadata:

  name: cpp-pgbouncer-eppoltp

  namespace: {{ .Release.Namespace }}

spec:

  type: ExternalName

  externalName: epp-pgbouncer-eppoltp.k8s-cppm.svc.cluster.local

---

apiVersion: v1

kind: Service

metadata:

  name: cpp-postgres-eppoltp

  namespace: {{ .Release.Namespace }}

spec:

  type: ExternalName

  externalName: epp-postgres-eppoltp.k8s-cppm.svc.cluster.local

---

apiVersion: v1

kind: Service

metadata:

  name: cpp-redis

  namespace: {{ .Release.Namespace }}

spec:

  type: ExternalName

  externalName: epp-redis.k8s-cppm.svc.cluster.local

