apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-cppm-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  hostPath:
    path: /data/cppm-nfs
