apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: clair-db
spec:
  replicas: {{ .Values.database.clairDb.replicas }}
  selector:
    matchLabels:
      app: clair-db
  template:
    metadata:
      labels:
        app: clair-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.nodeName | quote }}
      containers:
        - name: clair-db
          image: "ghcr.io/woobeom-lee/clair-db:latest"
          imagePullPolicy: {{ .Values.database.clairDb.image.pullPolicy }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: vol-clair-sql
              mountPath: /root/clair2x-vuln-db.sql
      volumes:
        - name: vol-clair-sql
          hostPath:
            path: {{ .Values.global.hostPathBase }}/permanent/clair/sql/clair2x-vuln-db.sql
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: clair-db
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: clair-db
