postgresql:
  enabled: true
  name: postgresql
  externalName: cpp-postgres-eppoltp.k8s-cppm.svc.cluster.local
  port: 8817
  database: cppoltp
  schema: cppm
  user: eppoltpuser
  password: "qweQWE123!@#"  # 담당자 확인 기본값 적용

mongodb:
  enabled: true
  name: mongodb
  externalName: cpp-mongo-mongos.k8s-cppm.svc.cluster.local
  port: 8825
  collection: eppnosqluser  # 통상적으로 DB명은 user명과 동일하게 세팅됩니다.
  user: eppnosqluser        # eppnosql -> eppnosqluser 로 수정
  password: "qwe123"        # 담당자 확인 기본값 적용

  externalList:
    primary00: cpp-mongo-mongos.k8s-cppm.svc.cluster.local
    secondary01: cpp-mongo-mongos.k8s-cppm.svc.cluster.local
    secondary02: cpp-mongo-mongos.k8s-cppm.svc.cluster.local
  ports:
    primary00: 8825
    secondary01: 8825
    secondary02: 8825
