{{- if .Values.dbInit.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.dbInit.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: {{ .Values.dbInit.restartPolicy | default "OnFailure" }}
      containers:
        - name: {{ .Values.dbInit.name }}
          image: {{ .Values.dbInit.repository }}:{{ .Values.dbInit.version }}
          imagePullPolicy: {{ .Values.dbInit.pullPolicy | default "IfNotPresent" }}
          envFrom:
          - secretRef:
              name: {{ .Values.dbInit.name }}-secret
          - configMapRef:
              name: {{ .Values.dbInit.name }}-env-cm
          volumeMounts:
          - name: nfs
            mountPath: /nfs
          - name: {{ .Values.dbInit.name }}-file-cm
            mountPath: /init
          command: [/bin/bash, /init/init.sh]
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-pvc
      - name: {{ .Values.dbInit.name }}-file-cm
        configMap:
          name: {{ .Values.dbInit.name }}-file-cm
          defaultMode: 0755
{{- end }}
