{{- if .Values.dbInit.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbInit.name }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
type: Opaque
data:
{{- if .Values.postgresql.enabled }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database | b64enc }}
  POSTGRESQL_SCHEMA: {{ .Values.postgresql.schema | b64enc }}
  POSTGRESQL_USER: {{ .Values.postgresql.user | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | b64enc }}
{{- end }}
{{- if .Values.mongodb.enabled }}
  MONGODB_COLLECTION: {{ .Values.mongodb.collection | b64enc }}
  MONGODB_USER: {{ .Values.mongodb.user | b64enc }}
  MONGODB_PASSWORD: {{ .Values.mongodb.password | b64enc }}
{{- end }}
{{- end }}
